# .github/FUNDING.yml

# Your GitHub username. This will activate once you are approved for GitHub Sponsors.
github: aaravaggarwal3535

# Your Ko-fi username (swap 'demo_placeholder' with your actual username when ready)
ko_fi: aarav_aggarwal