[build-system]
requires = ["setuptools>=64", "wheel", "pybind11>=2.10"]
build-backend = "setuptools.build_meta"

[project]
name = "aakaar"
version = "0.1.4"
description = "A custom CUDA-accelerated ML library"
readme = "README.md"
authors = [{name = "Aarav Aggarwal"}]
requires-python = ">=3.9"
dependencies = ["numpy"]
[project.optional-dependencies]
cuda = ["nvidia-curand-cu12", "nvidia-cuda-runtime-cu12"]