name: Build macOS Wheels

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_macos_wheels:
    name: Build wheels on macOS
    runs-on: macos-14   # Apple Silicon runner; use macos-13 for Intel

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OpenBLAS and libomp (via Homebrew)
        run: brew install openblas libomp

      - name: Build wheels
        uses: pypa/cibuildwheel@v4.1.0
        with:
          output-dir: dist
        env:
          CIBW_BUILD: "cp310-macosx_arm64 cp311-macosx_arm64 cp312-macosx_arm64 cp313-macosx_arm64 cp314-macosx_arm64"
          CIBW_ENVIRONMENT_MACOS: >
            CPATH=/opt/homebrew/opt/openblas/include
            LIBRARY_PATH=/opt/homebrew/opt/openblas/lib
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: "delocate-listdeps {wheel} && delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-wheels
          path: ./dist/*.whl  